--loadMaxFile "X:\Temp\新建文件夹\SimpleCube.max"
loadMaxFile "X:\工作\Max\cocosfinish2_攻击.max"
--loadMaxFile "X:\Dev\Models\Cocos\cocos-character\cocos-character\cocos-character\Max\cocosfinish_攻击.max"
--loadMaxFile "X:\Dev\Models\Cocos\Test.max"
--loadMaxFile "X:\Dev\Models\Cocos\Test - 副本.max"
--loadMaxFile "X:\Temp\10062\10062\10062_hit.max"
--loadMaxFile "X:\Temp\10062\10062_hit.max"
--loadMaxFile "X:\Temp\monster-001-蜘蛛\monster-001.max"
exportFile "X:\工作\Max\Export\中文路径.GLTF" #noPrompt