target("3dsMax-glTF-plugin")
    set_kind("binary")
    add_files("src/*.cpp")
    set_languages("cxx17")
    add_defines("UNICODE", "_UNICODE", "_USRDLL", "NOMINMAX", "PUGIXML_WCHAR_MODE")
    add_includedirs(adsk3dsMaxIncludeDir)
    add_packages("nlohmann_json")
    on_load(function (target)
        import("find3dsMaxSDK")
        adsk3dsMaxSDKHome = find3dsMaxSDK.find()
        if adsk3dsMaxSDKHome ~= nil then 
            print('3ds Max SDK: ' .. adsk3dsMaxSDKHome)
            adsk3dsMaxIncludeDir = path.join(adsk3dsMaxSDKHome, 'include')
            adsk3dsMaxLibDir = path.join(adsk3dsMaxSDKHome, 'lib', 'x64', 'Release')
            target:add("includedirs", adsk3dsMaxIncludeDir)
            target:add("linkdirs", adsk3dsMaxLibDir)
            target:add("links", 'core')
        end
    end)