
#pragma once

#define IDS_PLUGIN_DESCRIPTION 101
#define IDS_GLTF_EXPORTER_CLASS_NAME 102
#define IDS_GLTF_EXPORTER_INTERNAL_NAME 103
#define IDS_GLTF_EXPORTER_LONG_DESCRIPTION 104
#define IDS_GLTF_EXPORTER_SHORT_DESCRIPTION 105
#define IDS_GLTF_EXPORTER_AUTHOR_NAME 106
#define IDS_GLTF_EXPORTER_COPYRIGHT_MESSAGE 107
#define IDS_GLTF_EXPORTER_OTHER_MESSAGE_1 108
#define IDS_GLTF_EXPORTER_OTHER_MESSAGE_2 109
#define IDS_GLTF_EXPORTER_ABOUT 110